# Generated by Django 3.1.2 on 2022-01-31 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Provide 50x50 image in PNG format.', null=True, upload_to=files_management.models.get_file_path, verbose_name='image')),
                ('files_capacity_limit', models.PositiveIntegerField(default=1, help_text='Files capacity limit in megabytes.', verbose_name='files capacity limit')),
                ('app_notifications', models.BooleanField(default=True, verbose_name='app notifications')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('job_scheduler_app_notifications', models.BooleanField(default=False, verbose_name='job scheduler app notifications')),
                ('job_scheduler_email_notifications', models.BooleanField(default=False, verbose_name='job scheduler email notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
