# Generated by Django 3.1.2 on 2021-10-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='SubordinateDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ParentDepartment', to='company_structure.department', verbose_name='parent department')),
                ('subordinate_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubordinateDepartment', to='company_structure.department', verbose_name='subordinate department')),
            ],
            options={
                'verbose_name': 'subordinate department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone_number', models.CharField(blank=True, max_length=15, verbose_name='cell phone number')),
                ('internal_phone_number', models.CharField(blank=True, max_length=15, verbose_name='internal phone number')),
                ('additional_phone_number', models.CharField(blank=True, max_length=15, verbose_name='additional phone number')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='stanowisko')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('registration_number', models.CharField(blank=True, max_length=20, verbose_name='registration number')),
                ('region_name', models.CharField(blank=True, default='', max_length=50, verbose_name='region name')),
                ('region_code', models.CharField(blank=True, default='', max_length=15, verbose_name='region code')),
                ('cities', models.CharField(blank=True, default='', max_length=1000, verbose_name='cities')),
                ('short_cell_phone_number', models.CharField(blank=True, default='', max_length=5, verbose_name='short cell phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'permissions': (('can_fill_employee_additional_data', 'Can fill additional employee data'),),
            },
        ),
        migrations.CreateModel(
            name='DepartmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(choices=[(1, 'Member'), (2, 'Deputy Manager'), (3, 'Manager')], default=1, verbose_name='role')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.department', verbose_name='department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'department member',
                'verbose_name_plural': 'department members',
            },
        ),
    ]
