# Generated by Django 3.1.2 on 2022-02-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='region name'),
        ),
    ]
