# Generated by Django 3.1.2 on 2022-01-31 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='city')),
            ],
            options={
                'verbose_name': 'company settings',
                'verbose_name_plural': 'company settings',
            },
        ),
        migrations.CreateModel(
            name='ConferenceRoomsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('start_hour', models.PositiveIntegerField(verbose_name='start hour')),
                ('end_hour', models.PositiveIntegerField(verbose_name='end hour')),
                ('desired_rooms_number', models.PositiveIntegerField(verbose_name='desired rooms number')),
            ],
            options={
                'verbose_name': 'conference rooms settings',
                'verbose_name_plural': 'conference rooms settings',
            },
        ),
        migrations.CreateModel(
            name='FilesManagementSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('max_file_size', models.PositiveIntegerField(help_text='Maximum file size in megabytes.', verbose_name='max file size')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('weeks', models.IntegerField(default=0, verbose_name='weeks')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('hours', models.IntegerField(default=0, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='next run time')),
            ],
            options={
                'verbose_name': 'files management settings',
                'verbose_name_plural': 'files management settings',
            },
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('website_name', models.CharField(max_length=100, verbose_name='website name')),
                ('admin_website_name', models.CharField(max_length=100, verbose_name='admin website name')),
                ('logo', models.ImageField(default='default_logo.png', help_text='Image should be in PNG format.', upload_to='global_live_settings/uploads', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'general settings',
                'verbose_name_plural': 'general settings',
            },
        ),
        migrations.CreateModel(
            name='GlpiIntegrationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('url', models.CharField(max_length=300, verbose_name='url')),
                ('authorization', models.CharField(max_length=100, verbose_name='authorization')),
                ('app_token', models.CharField(max_length=100, verbose_name='app token')),
                ('parent_groups_names_to_sync', models.CharField(max_length=500, verbose_name='parent groups names to sync')),
                ('user_account_sync_group', models.CharField(max_length=100, verbose_name='user account sync group')),
                ('user_data_sync_group', models.CharField(max_length=100, verbose_name='user_data_sync_group')),
                ('user_data_sync_from_comment_group', models.CharField(max_length=100, verbose_name='user_data_sync_from_comment_group')),
                ('comment_data_start_separator', models.CharField(max_length=30, verbose_name='comment data start separator')),
                ('comment_data_end_separator', models.CharField(max_length=30, verbose_name='comment data end separator')),
                ('region_name_api_key', models.CharField(max_length=30, verbose_name='region name api key')),
                ('region_code_api_key', models.CharField(max_length=30, verbose_name='region code api key')),
                ('cities_api_key', models.CharField(max_length=30, verbose_name='cities api key')),
                ('short_cell_phone_number_api_key', models.CharField(max_length=30, verbose_name='short cell phone number api key')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('weeks', models.IntegerField(default=0, verbose_name='weeks')),
                ('days', models.IntegerField(default=0, verbose_name='days')),
                ('hours', models.IntegerField(default=1, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='next run time')),
            ],
            options={
                'verbose_name': 'GLPI integration settings',
                'verbose_name_plural': 'GLPI integration settings',
            },
        ),
        migrations.CreateModel(
            name='NotifierSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('email_subject_prefix', models.CharField(blank=True, max_length=150, verbose_name='email subject prefix')),
                ('email_subject_suffix', models.CharField(blank=True, max_length=150, verbose_name='email subject suffix')),
                ('email_footer', models.TextField(blank=True, verbose_name='email footer')),
            ],
            options={
                'verbose_name': 'notifier settings',
                'verbose_name_plural': 'notifier settings',
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='url')),
                ('position', models.PositiveSmallIntegerField(unique=True, verbose_name='position')),
            ],
            options={
                'verbose_name': 'useful link',
                'verbose_name_plural': 'useful links',
            },
        ),
        migrations.CreateModel(
            name='AbsenceCalendarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('weeks', models.IntegerField(default=0, verbose_name='weeks')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('hours', models.IntegerField(default=0, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='next run time')),
                ('payroll_department_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='payroll department group')),
            ],
            options={
                'verbose_name': 'absence calendar settings',
                'verbose_name_plural': 'absence calendar settings',
            },
        ),
    ]
