# Generated by Django 3.1.2 on 2022-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiersettings',
            name='days',
            field=models.IntegerField(default=1, verbose_name='days'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='enabled'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='hours'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='minutes',
            field=models.IntegerField(default=0, verbose_name='minutes'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='next_run_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next run time'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='remove_only_checked',
            field=models.BooleanField(default=True, verbose_name='remove only checked'),
        ),
        migrations.AddField(
            model_name='notifiersettings',
            name='weeks',
            field=models.IntegerField(default=0, verbose_name='weeks'),
        ),
    ]
