# Generated by Django 3.1.2 on 2022-06-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_settings', '0002_auto_20220628_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifiersettings',
            name='remove_older_than',
            field=models.IntegerField(default=3, help_text='months', verbose_name='remove older than'),
        ),
    ]
