# Generated by Django 3.1.2 on 2022-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_settings', '0003_notifiersettings_remove_older_than'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifiersettings',
            name='remove_older_than',
            field=models.IntegerField(default=12, help_text='Weeks', verbose_name='remove older than'),
        ),
    ]
