# Generated by Django 3.1.2 on 2022-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_settings', '0004_auto_20220628_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggingSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('remove_older_than', models.IntegerField(default=26, help_text='Weeks', verbose_name='remove older than')),
                ('weeks', models.IntegerField(default=0, verbose_name='weeks')),
                ('days', models.IntegerField(default=1, verbose_name='days')),
                ('hours', models.IntegerField(default=0, verbose_name='hours')),
                ('minutes', models.IntegerField(default=0, verbose_name='minutes')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='next run time')),
            ],
            options={
                'verbose_name': 'logging settings',
                'verbose_name_plural': 'logging settings',
            },
        ),
    ]
