# Generated by Django 3.1.2 on 2023-04-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_settings', '0005_loggingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencecalendarsettings',
            name='personal_data_protection_url',
            field=models.URLField(default='#', verbose_name='personal data protection URL'),
        ),
        migrations.AddField(
            model_name='absencecalendarsettings',
            name='risk_assessment_url',
            field=models.URLField(default='#', verbose_name='risk assessment URL'),
        ),
        migrations.AddField(
            model_name='absencecalendarsettings',
            name='safety_rules_url',
            field=models.URLField(default='#', verbose_name='safety rules URL'),
        ),
    ]
