# Generated by Django 3.1.2 on 2021-10-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlpiDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_group_id', models.PositiveIntegerField(unique=True, verbose_name='GLPI group ID')),
                ('glpi_last_modification_date', models.CharField(max_length=50, verbose_name='GLPI last modification date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_structure.department', verbose_name='department')),
            ],
            options={
                'verbose_name': 'GLPI department',
                'verbose_name_plural': 'GLPI departments',
            },
        ),
        migrations.CreateModel(
            name='GlpiSubordinateDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_parent_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GlpiParentDepartment', to='glpi_integration.glpidepartment', verbose_name='GLPI parent department')),
                ('glpi_subordinate_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GlpiSubordinateDepartment', to='glpi_integration.glpidepartment', verbose_name='GLPI subordinate department')),
            ],
            options={
                'verbose_name': 'GLPI subordinate department',
                'verbose_name_plural': 'GLPI subordinate departments',
            },
        ),
        migrations.CreateModel(
            name='GlpiEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_user_id', models.PositiveIntegerField(unique=True, verbose_name='GLPI user ID')),
                ('glpi_last_modification_date', models.CharField(max_length=50, verbose_name='GLPI last modification date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='glpi_employee', to='company_structure.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'GLPI employee',
                'verbose_name_plural': 'GLPI employees',
            },
        ),
        migrations.CreateModel(
            name='GlpiDepartmentMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glpi_relation_id', models.PositiveIntegerField(unique=True, verbose_name='GLPI relation ID')),
                ('role', models.IntegerField(choices=[(1, 'Member'), (2, 'Deputy Manager'), (3, 'Manager')], default=1, verbose_name='GLPI role')),
                ('glpi_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glpi_integration.glpidepartment', verbose_name='GLPI department')),
                ('glpi_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glpi_integration.glpiemployee', verbose_name='GLPI employee')),
            ],
            options={
                'verbose_name': 'GLPI deparment member',
                'verbose_name_plural': 'GLPI department members',
            },
        ),
    ]
