# Generated by Django 3.1.2 on 2021-10-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import files_management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntranetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('file', models.FileField(upload_to=files_management.models.get_file_path, verbose_name='file')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date')),
                ('added_with_wysiwyg', models.BooleanField(default=False, verbose_name='added with wysiwyg')),
                ('usage_counter', models.IntegerField(default=0, verbose_name='usage counter')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='file size')),
                ('extension', models.CharField(blank=True, default='', max_length=20, verbose_name='extension')),
                ('file_content_hash', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='file content hash')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'intranet file',
                'verbose_name_plural': 'intranet files',
            },
        ),
    ]
