# Generated by Django 3.1.2 on 2022-06-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='checked'),
        ),
    ]
