# Generated by Django 3.1.2 on 2022-01-31 11:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'absence type',
                'verbose_name_plural': 'absence types',
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveConfirmationDocumentName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('text_in_application', models.TextField(verbose_name='text in application')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'special leave confirmation document name',
                'verbose_name_plural': 'special leave confirmation document names',
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(verbose_name='document ID')),
                ('absent_name', models.CharField(max_length=250, verbose_name='absent name')),
                ('registration_number', models.CharField(max_length=20, verbose_name='registration number')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('date_of_completion', models.DateField(verbose_name='date of completion')),
                ('company_name', models.CharField(max_length=100, verbose_name='company name')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='number of days')),
                ('reason', models.TextField(verbose_name='reason')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('decisive_name', models.CharField(max_length=250, verbose_name='decisive name')),
                ('confirmation_document_name', models.TextField(verbose_name='confirmation document name')),
                ('confirmation_document_number', models.CharField(max_length=30, verbose_name='confirmation document number')),
                ('confirmation_document_issue_date', models.DateField(verbose_name='confirmation document issue date')),
                ('confirming_person_name', models.CharField(max_length=250, verbose_name='confirming person name')),
            ],
            options={
                'verbose_name': 'special leave document',
                'verbose_name_plural': 'special leave documents',
            },
        ),
        migrations.CreateModel(
            name='SpecialLeaveReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('text_in_application', models.TextField(verbose_name='text in application')),
                ('max_number_of_days', models.PositiveIntegerField(verbose_name='max number of days')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
            ],
            options={
                'verbose_name': 'special leave reason',
                'verbose_name_plural': 'special leave reasons',
            },
        ),
        migrations.CreateModel(
            name='VacationLeaveDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(verbose_name='document ID')),
                ('absent_name', models.CharField(max_length=250, verbose_name='absent name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('leave_for_year', models.PositiveIntegerField(verbose_name='leave for year')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='number of days')),
                ('vacation_leave_type', models.TextField(verbose_name='vacation leave type')),
                ('decisive_name', models.CharField(max_length=250, verbose_name='decisive name')),
                ('date_of_completion', models.DateField(verbose_name='date of completion')),
                ('registration_number', models.CharField(max_length=20, verbose_name='registration number')),
                ('department_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='department name')),
                ('department_manager_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='department manager name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
            ],
            options={
                'verbose_name': 'vacation leave document',
                'verbose_name_plural': 'vacation leave documents',
            },
        ),
        migrations.CreateModel(
            name='VacationLeaveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('max_number_of_days', models.PositiveIntegerField(verbose_name='max number of days')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'vacation leave type',
                'verbose_name_plural': 'vacation leave types',
            },
        ),
        migrations.CreateModel(
            name='VacationLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('leave_for_year', models.PositiveIntegerField(default=2020, validators=[django.core.validators.MinValueValidator(2019), django.core.validators.MaxValueValidator(9999)], verbose_name='leave for year')),
                ('number_of_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of days')),
                ('message_for_decisive_person', models.TextField(blank=True, verbose_name='message for decisive person')),
                ('date_of_completion', models.DateField(default=django.utils.timezone.now, verbose_name='date of completion')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Canceled'), (5, 'Canceled by decisive person'), (6, 'Pending to cancel'), (7, 'Pending to finish earlier')], default=1, verbose_name='status')),
                ('last_status_change_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last status change time')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('pending_end_date', models.DateField(blank=True, null=True, verbose_name='pending end date')),
                ('pending_number_of_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='pending number of days')),
                ('absent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='VLEmployee', to=settings.AUTH_USER_MODEL, verbose_name='absent')),
                ('decisive_person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VLDecisive', to=settings.AUTH_USER_MODEL, verbose_name='decisive person')),
                ('document', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacation_leave', to='absence_calendar.vacationleavedocument', verbose_name='document')),
                ('status_changed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VLSupervisor', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
                ('vacation_leave_type', models.ForeignKey(limit_choices_to={'visible': True}, on_delete=django.db.models.deletion.PROTECT, to='absence_calendar.vacationleavetype', verbose_name='vacation leave type')),
            ],
            options={
                'verbose_name': 'vacation leave',
                'verbose_name_plural': 'vacation leaves',
                'permissions': (('moderate_vacation_leave', 'Can moderate vacation leaves'), ('view_vacation_leave_document', 'Can view vacation leave document')),
            },
        ),
        migrations.CreateModel(
            name='SpecialLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('number_of_days', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of days')),
                ('date_of_completion', models.DateField(default=django.utils.timezone.now, verbose_name='date of completion')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Canceled'), (5, 'Canceled by decisive person'), (6, 'Confirmed'), (7, 'Pending to cancel'), (8, 'Pending to finish earlier')], default=1, verbose_name='status')),
                ('last_status_change_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last status change time')),
                ('message_for_decisive_person', models.TextField(blank=True, verbose_name='message for decisive person')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('pending_end_date', models.DateField(blank=True, null=True, verbose_name='pending end date')),
                ('pending_number_of_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='pending number of days')),
                ('confirmation_document_number', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='confirmation document number')),
                ('confirmation_document_issue_date', models.DateField(blank=True, default=None, null=True, verbose_name='confirmation document issue date')),
                ('absent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SLEmployee', to=settings.AUTH_USER_MODEL, verbose_name='absent')),
                ('confirmation_document_name', models.ForeignKey(blank=True, default=None, limit_choices_to={'visible': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='absence_calendar.specialleaveconfirmationdocumentname', verbose_name='confirmation document name')),
                ('confirming_person', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SLConfirming', to=settings.AUTH_USER_MODEL, verbose_name='confirming person')),
                ('decisive_person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SLDecisive', to=settings.AUTH_USER_MODEL, verbose_name='decisive person')),
                ('document', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_leave', to='absence_calendar.specialleavedocument', verbose_name='document')),
                ('reason', models.ForeignKey(limit_choices_to={'visible': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='absence_calendar.specialleavereason', verbose_name='reason')),
                ('status_changed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SLSupervisor', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
            ],
            options={
                'verbose_name': 'special leave',
                'verbose_name_plural': 'special leaves',
                'permissions': (('moderate_special_leave', 'Can moderate special leaves'), ('view_special_leave_document', 'Can view special leave document')),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='tytuł')),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('additional_information', models.TextField(blank=True, verbose_name='additional information')),
                ('absence_type', models.ForeignKey(limit_choices_to={'visible': True}, on_delete=django.db.models.deletion.PROTECT, to='absence_calendar.absencetype', verbose_name='absence type')),
                ('absent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='absent')),
            ],
            options={
                'verbose_name': 'absence',
                'verbose_name_plural': 'absences',
            },
        ),
    ]
