# Generated by Django 3.1.2 on 2022-06-03 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialleave',
            name='number_of_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of days'),
        ),
        migrations.AlterField(
            model_name='vacationleave',
            name='number_of_days',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of days'),
        ),
    ]
