# Generated by Django 3.1.2 on 2023-03-31 07:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence_calendar', '0002_auto_20220603_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteWorkDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.PositiveIntegerField(verbose_name='document ID')),
                ('absent_name', models.CharField(max_length=250, verbose_name='absent name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('number_of_days', models.PositiveIntegerField(verbose_name='number of days')),
                ('decisive_name', models.CharField(max_length=250, verbose_name='decisive name')),
                ('date_of_completion', models.DateField(verbose_name='date of completion')),
                ('registration_number', models.CharField(max_length=20, verbose_name='registration number')),
                ('department_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='department name')),
                ('department_manager_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='department manager name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
            ],
            options={
                'verbose_name': 'remote work document',
                'verbose_name_plural': 'remote work documents',
            },
        ),
        migrations.CreateModel(
            name='RemoteWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('number_of_days', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of days')),
                ('message_for_decisive_person', models.TextField(blank=True, verbose_name='message for decisive person')),
                ('date_of_completion', models.DateField(default=django.utils.timezone.now, verbose_name='date of completion')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Canceled'), (5, 'Canceled by decisive person'), (6, 'Pending to cancel'), (7, 'Pending to finish earlier')], default=1, verbose_name='status')),
                ('last_status_change_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last status change time')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('pending_end_date', models.DateField(blank=True, null=True, verbose_name='pending end date')),
                ('pending_number_of_days', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='pending number of days')),
                ('absent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='RWEmployee', to=settings.AUTH_USER_MODEL, verbose_name='absent')),
                ('decisive_person', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RWDecisive', to=settings.AUTH_USER_MODEL, verbose_name='decisive person')),
                ('document', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remote_work', to='absence_calendar.remoteworkdocument', verbose_name='document')),
                ('status_changed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RWSupervisor', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
            ],
            options={
                'verbose_name': 'remote work',
                'verbose_name_plural': 'remote works',
                'permissions': (('moderate_remote_work', 'Can moderate remote works'), ('view_remote_work_document', 'Can view remote work document')),
            },
        ),
    ]
