# Generated by Django 3.1.2 on 2023-03-31 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('absence_calendar', '0003_remotework_remoteworkdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotework',
            name='status_changed_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RWStatusChangedBy', to=settings.AUTH_USER_MODEL, verbose_name='status changed by'),
        ),
    ]
