# Generated by Django 3.1.2 on 2023-03-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence_calendar', '0004_auto_20230331_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotework',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='apartment number'),
        ),
        migrations.AddField(
            model_name='remotework',
            name='city',
            field=models.CharField(default=1, max_length=50, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotework',
            name='country',
            field=models.CharField(default=1, max_length=50, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotework',
            name='house_number',
            field=models.CharField(default=1, max_length=10, verbose_name='house number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotework',
            name='postal_code',
            field=models.CharField(default=1, max_length=20, verbose_name='postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotework',
            name='street',
            field=models.CharField(default=1, max_length=100, verbose_name='street'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='apartment number'),
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_city',
            field=models.CharField(default=1, max_length=50, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_country',
            field=models.CharField(default=1, max_length=50, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_house_number',
            field=models.CharField(default=1, max_length=10, verbose_name='house number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_postal_code',
            field=models.CharField(default=1, max_length=20, verbose_name='postal code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remoteworkdocument',
            name='address_street',
            field=models.CharField(default=1, max_length=100, verbose_name='street'),
            preserve_default=False,
        ),
    ]
