# Generated by Django 3.1.2 on 2021-12-16 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, verbose_name='job id')),
                ('log_status', models.CharField(max_length=25, verbose_name='log status')),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='log time')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'job log',
                'verbose_name_plural': 'job logs',
            },
        ),
    ]
