import django.dispatch


vacation_leave_pending = django.dispatch.Signal()
vacation_leave_deleted = django.dispatch.Signal()
vacation_leave_accepted = django.dispatch.Signal()
vacation_leave_rejected = django.dispatch.Signal()
accepted_vacation_leave_updated = django.dispatch.Signal()
vacation_leave_decisive_changed = django.dispatch.Signal()
vacation_leave_decision_changed_accepted = django.dispatch.Signal()
vacation_leave_decision_changed_rejected = django.dispatch.Signal()
vacation_leave_pending_to_cancel = django.dispatch.Signal()
vacation_leave_canceled = django.dispatch.Signal()
vacation_leave_cancelation_rejected = django.dispatch.Signal()
vacation_leave_finished_earlier = django.dispatch.Signal()
vacation_leave_pending_to_finish_earlier = django.dispatch.Signal()
vacation_leave_request_to_finish_earlier_rejected = django.dispatch.Signal()

special_leave_pending = django.dispatch.Signal()
special_leave_deleted = django.dispatch.Signal()
special_leave_accepted = django.dispatch.Signal()
special_leave_rejected = django.dispatch.Signal()
accepted_special_leave_updated = django.dispatch.Signal()
special_leave_decisive_changed = django.dispatch.Signal()
special_leave_decision_changed_accepted = django.dispatch.Signal()
special_leave_decision_changed_rejected = django.dispatch.Signal()
special_leave_confirmation_document_confirmed = django.dispatch.Signal()
special_leave_pending_to_cancel = django.dispatch.Signal()
special_leave_canceled = django.dispatch.Signal()
special_leave_cancelation_rejected = django.dispatch.Signal()
special_leave_finished_earlier = django.dispatch.Signal()
special_leave_pending_to_finish_earlier = django.dispatch.Signal()
special_leave_request_to_finish_earlier_rejected = django.dispatch.Signal()

remote_work_pending = django.dispatch.Signal()
remote_work_deleted = django.dispatch.Signal()
remote_work_accepted = django.dispatch.Signal()
remote_work_rejected = django.dispatch.Signal()
accepted_remote_work_updated = django.dispatch.Signal()
remote_work_decisive_changed = django.dispatch.Signal()
remote_work_decision_changed_accepted = django.dispatch.Signal()
remote_work_decision_changed_rejected = django.dispatch.Signal()
remote_work_pending_to_cancel = django.dispatch.Signal()
remote_work_canceled = django.dispatch.Signal()
remote_work_cancelation_rejected = django.dispatch.Signal()
remote_work_finished_earlier = django.dispatch.Signal()
remote_work_pending_to_finish_earlier = django.dispatch.Signal()
remote_work_request_to_finish_earlier_rejected = django.dispatch.Signal()
