from django.urls import path
from . import views


app_name = 'absence_calendar'

urlpatterns = [
    path('event/new/', views.EventCreateView.as_view(), name='event_create'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name='event_detail'),
    path('event/<int:pk>/update/', views.EventUpdateView.as_view(), name='event_update'),
    path('event/<int:pk>/delete/', views.EventDeleteView.as_view(), name='event_delete'),

    path('absence/new/', views.AbsenceCreateView.as_view(), name='absence_create'),
    path('absence/<int:pk>/update/', views.AbsenceUpdateView.as_view(), name='absence_update'),
    path('absence/<int:pk>/', views.AbsenceDetailView.as_view(), name='absence_detail'),
    path('absence/<int:pk>/delete/', views.AbsenceDeleteView.as_view(), name='absence_delete'),
    path('absence/<int:pk>/finish_earlier/', views.AbsenceFinishEarlierView.as_view(), name='absence_finish_earlier'),
    path('user_absences/', views.UserAbsencesListView.as_view(), name='user_absences'),
    path('absence_by_manager/new/', views.AbsenceByManagerCreateView.as_view(), name='absence_by_manager_create'),
    path('absence_by_manager/<int:pk>/delete/', views.AbsenceByManagerDeleteView.as_view(), name='absence_by_manager_delete'),

    path('vacation_leave/new/', views.VacationLeaveCreateView.as_view(), name='vacation_leave_create'),
    path('vacation_leave/<int:pk>/update/', views.VacationLeaveUpdateView.as_view(), name='vacation_leave_update'),
    path('vacation_leave/<int:pk>/', views.VacationLeaveDetailView.as_view(), name='vacation_leave_detail'),
    path('vacation_leave/<int:pk>/delete/', views.VacationLeaveDeleteView.as_view(), name='vacation_leave_delete'),
    path('vacation_leave/<int:pk>/cancel/', views.VacationLeaveCancelView.as_view(), name='vacation_leave_cancel'),
    path('vacation_leave/<int:pk>/finish_earlier/', views.VacationLeaveFinishEarlierView.as_view(), name='vacation_leave_finish_earlier'),
    path('moderation/vacation_leaves/', views.VacationLeavesModerationListView.as_view(), name='vacation_leaves_moderation'),
    path('vacation_leave/<int:id>/accept/', views.VacationLeaveAcceptAjaxView.as_view(), name='vacation_leave_accept_ajax'),
    path('vacation_leave/<int:id>/reject/', views.VacationLeaveRejectAjaxView.as_view(), name='vacation_leave_reject_ajax'),
    path('vacation_leave/<int:id>/accept_cancelation/', views.VacationLeaveAcceptCancelationAjaxView.as_view(),
                                                                name='vacation_leave_accept_cancelation_ajax'),
    path('vacation_leave/<int:id>/reject_cancelation/', views.VacationLeaveRejectCancelationAjaxView.as_view(),
                                                                name='vacation_leave_reject_cancelation_ajax'),
    path('vacation_leave/<int:id>/accept_finish_earlier/', views.VacationLeaveAcceptFinishEarlierAjaxView.as_view(),
                                                                name='vacation_leave_accept_finish_earlier_ajax'),
    path('vacation_leave/<int:id>/reject_finish_earlier/', views.VacationLeaveRejectFinishEarlierAjaxView.as_view(),
                                                                name='vacation_leave_reject_finish_earlier_ajax'),
    path('vacation_leaves/previously_processed/', views.VacationLeavesPreviouslyProcessedListView.as_view(), 
                                                                name='vacation_leaves_previously_processed'),
    path('vacation_leave/<int:id>/change_decision/accept/', views.VacationLeaveChangeDecisionAcceptAjaxView.as_view(),
                                                                    name='vacation_leave_change_decision_accept_ajax'),
    path('vacation_leave/<int:id>/change_decision/reject/', views.VacationLeaveChangeDecisionRejectAjaxView.as_view(),
                                                                    name='vacation_leave_change_decision_reject_ajax'),
    path('vacation_leaves/applications/', views.VacationLeavesApplicationsListView.as_view(), name='vacation_leaves_applications'),
    path('vacation_leave/<int:pk>/application/', views.VacationLeaveApplicationDetailView.as_view(), name='vacation_leave_application'),
    path('vacation_leave/<int:vacation_leave_id>/application/pdf/', views.vacation_leave_application_pdf, name='vacation_leave_application_pdf'),
    path('vacation_leaves/applications/pdf/', views.vacation_leaves_applications_pdf, name='vacation_leaves_applications_pdf'),
    path('user_vacation_leaves/', views.UserVacationLeavesListView.as_view(), name='user_vacation_leaves'),

    path('special_leave/new/', views.SpecialLeaveCreateView.as_view(), name='special_leave_create'),
    path('special_leave/<int:pk>/update/', views.SpecialLeaveUpdateView.as_view(), name='special_leave_update'),
    path('special_leave/<int:pk>/', views.SpecialLeaveDetailView.as_view(), name='special_leave_detail'),
    path('special_leave/<int:pk>/delete/', views.SpecialLeaveDeleteView.as_view(), name='special_leave_delete'),
    path('special_leave/<int:pk>/cancel/', views.SpecialLeaveCancelView.as_view(), name='special_leave_cancel'),
    path('special_leave/<int:pk>/finish_earlier/', views.SpecialLeaveFinishEarlierView.as_view(), name='special_leave_finish_earlier'),
    path('moderation/special_leaves/', views.SpecialLeavesModerationListView.as_view(), name='special_leaves_moderation'),
    path('special_leave/<int:id>/accept/', views.SpecialLeaveAcceptAjaxView.as_view(), name='special_leave_accept_ajax'),
    path('special_leave/<int:id>/reject/', views.SpecialLeaveRejectAjaxView.as_view(), name='special_leave_reject_ajax'),
    path('special_leave/<int:id>/accept_cancelation/', views.SpecialLeaveAcceptCancelationAjaxView.as_view(),
                                                                name='special_leave_accept_cancelation_ajax'),
    path('special_leave/<int:id>/reject_cancelation/', views.SpecialLeaveRejectCancelationAjaxView.as_view(),
                                                                name='special_leave_reject_cancelation_ajax'),
    path('special_leave/<int:id>/accept_finish_earlier/', views.SpecialLeaveAcceptFinishEarlierAjaxView.as_view(),
                                                                name='special_leave_accept_finish_earlier_ajax'),
    path('special_leave/<int:id>/reject_finish_earlier/', views.SpecialLeaveRejectFinishEarlierAjaxView.as_view(),
                                                                name='special_leave_reject_finish_earlier_ajax'),
    path('special_leaves/previously_processed/', views.SpecialLeavesPreviouslyProcessedListView.as_view(), name='special_leaves_previously_processed'),
    path('special_leave/<int:id>/change_decision/accept/', views.SpecialLeaveChangeDecisionAcceptAjaxView.as_view(), 
                                                                    name='special_leave_change_decision_accept_ajax'),
    path('special_leave/<int:id>/change_decision/reject/', views.SpecialLeaveChangeDecisionRejectAjaxView.as_view(), 
                                                                    name='special_leave_change_decision_reject_ajax'),
    path('special_leaves/applications/', views.SpecialLeavesApplicationsListView.as_view(), name='special_leaves_applications'),
    path('special_leave/<int:pk>/application/', views.SpecialLeaveApplicationDetailView.as_view(), name='special_leave_application'),
    path('special_leave/<int:special_leave_id>/application/pdf/', views.special_leave_application_pdf, name='special_leave_application_pdf'),
    path('special_leaves/applications/pdf/', views.special_leaves_applications_pdf, name='special_leaves_applications_pdf'),
    path('user_special_leaves/', views.UserSpecialLeavesListView.as_view(), name='user_special_leaves'),
    path('special_leave/<int:pk>/update/confirmation_document', views.SpecialLeaveUpdateConfirmationDocumentData.as_view(),
                                                                            name='special_leave_update_confirmation_document'),
    path('special_leave/<int:id>/confirm_document/', views.SpecialLeaveConfirmDocumentAjaxView.as_view(), name='special_leave_confirm_document_ajax'),

    path('remote_work/new/', views.RemoteWorkCreateView.as_view(), name='remote_work_create'),
    path('remote_work/<int:pk>/', views.RemoteWorkDetailView.as_view(), name='remote_work_detail'),
    path('remote_work/<int:pk>/update/', views.RemoteWorkUpdateView.as_view(), name='remote_work_update'),
    path('remote_work/<int:pk>/delete/', views.RemoteWorkDeleteView.as_view(), name='remote_work_delete'),
    path('remote_work/<int:pk>/cancel/', views.RemoteWorkCancelView.as_view(), name='remote_work_cancel'),
    path('remote_work/<int:pk>/finish_earlier/', views.RemoteWorkFinishEarlierView.as_view(), name='remote_work_finish_earlier'),
    path('moderation/remote_work/', views.RemoteWorkModerationListView.as_view(), name='remote_work_moderation'),
    path('remote_work/<int:id>/accept/', views.RemoteWorkAcceptAjaxView.as_view(), name='remote_work_accept_ajax'),
    path('remote_work/<int:id>/reject/', views.RemoteWorkRejectAjaxView.as_view(), name='remote_work_reject_ajax'),
    path('remote_work/<int:id>/accept_cancelation/', views.RemoteWorkAcceptCancelationAjaxView.as_view(),
                                                                name='remote_work_accept_cancelation_ajax'),
    path('remote_work/<int:id>/reject_cancelation/', views.RemoteWorkRejectCancelationAjaxView.as_view(),
                                                                name='remote_work_reject_cancelation_ajax'),
    path('remote_work/<int:id>/accept_finish_earlier/', views.RemoteWorkAcceptFinishEarlierAjaxView.as_view(),
                                                                name='remote_work_accept_finish_earlier_ajax'),
    path('remote_work/<int:id>/reject_finish_earlier/', views.RemoteWorkRejectFinishEarlierAjaxView.as_view(),
                                                                name='remote_work_reject_finish_earlier_ajax'),
    path('remote_works/previously_processed/', views.RemoteWorksPreviouslyProcessedListView.as_view(), 
                                                                name='remote_works_previously_processed'),
    path('remote_work/<int:id>/change_decision/accept/', views.RemoteWorkChangeDecisionAcceptAjaxView.as_view(),
                                                                    name='remote_work_change_decision_accept_ajax'),
    path('remote_work/<int:id>/change_decision/reject/', views.RemoteWorkChangeDecisionRejectAjaxView.as_view(),
                                                                    name='remote_work_change_decision_reject_ajax'),
    path('remote_works/applications/', views.RemoteWorksApplicationsListView.as_view(), name='remote_works_applications'),
    path('remote_work/<int:pk>/application/', views.RemoteWorkApplicationDetailView.as_view(), name='remote_work_application'),
    path('remote_work/<int:remote_work_id>/application/pdf/', views.remote_work_application_pdf, name='remote_work_application_pdf'),
    path('remote_works/applications/pdf/', views.remote_works_applications_pdf, name='remote_works_applications_pdf'),
    path('user_remote_works/', views.UserRemoteWorksListView.as_view(), name='user_remote_works'),

    path('<str:year>/<str:month>/', views.absence_calendar, name='absence_calendar'),
    path('<str:year>/<str:month>/<str:day>/', views.absence_calendar_day, name='absence_calendar_day'),
]
