"""
Django settings for intranet_project project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys
import ldap, logging
from django_auth_ldap.config import LDAPSearch, ActiveDirectoryGroupType
from django.contrib.messages import constants as message_constants
from django.utils.translation import gettext_lazy as _


# COMMAND RUN INFO

MIGRATION_COMMAND = sys.argv[1] in ('makemigrations', 'migrate')

# LDAP

GROUP_INTRANET_ADMINS = ''
GROUP_INTRANET_MEETINGS_MODERATORS = ''
GROUP_PAYROLL_DEPARTMENT = ''
GROUP_INTRANET_BANNED = ''
GROUP_INTRANET_EMPLOYEE_ADDITIONAL_INFO_PROVIDERS = ''

AUTH_LDAP_SERVER_URI = 'ldap://'
AUTH_LDAP_BIND_DN = 'CN=,OU=,OU=,DC=,DC='
AUTH_LDAP_BIND_PASSWORD = ''
AUTH_LDAP_USER_SEARCH = LDAPSearch('OU=,DC=,DC=', ldap.SCOPE_SUBTREE, '(sAMAccountName=%(user)s)',)

AUTH_LDAP_USER_ATTR_MAP = {
    'username': 'sAMAccountName',
    'first_name': 'givenName',
    'last_name': 'sn',
    #'email': 'mail',
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch (
    'ou=,ou=,dc=,dc=', ldap.SCOPE_SUBTREE, '(objectCategory=)'
)
AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr='cn')
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    'is_superuser': f'cn={GROUP_INTRANET_ADMINS},ou=,ou=,dc=,dc=',
    'is_staff': [
        f'cn={GROUP_INTRANET_ADMINS},ou=,ou=,dc=,dc=',
    ]
}

AUTH_LDAP_DENY_GROUP = f'cn={GROUP_INTRANET_BANNED},ou=,ou=,dc=,dc='
#AUTH_LDAP_FIND_GROUP_PERMS = True
#AUTH_LDAP_CACHE_GROUPS = True
#AUTH_LDAP_CACHE_TIMEOUT = 1#3600
AUTH_LDAP_ALWAYS_UPDATE_USER = True

AUTH_LDAP_MIRROR_GROUPS = [
    GROUP_INTRANET_ADMINS,
    GROUP_INTRANET_MEETINGS_MODERATORS,
    GROUP_PAYROLL_DEPARTMENT,
    GROUP_INTRANET_EMPLOYEE_ADDITIONAL_INFO_PROVIDERS,
]

AUTHENTICATION_BACKENDS = (
    'django_auth_ldap.backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1',]

# Application definition

INSTALLED_APPS = [
    'channels',
    'live_settings.apps.LiveSettingsConfig',
    'scheduler.apps.SchedulerConfig',
    'intranet.apps.IntranetConfig',
    'users.apps.UsersConfig',
    'custom_pages.apps.CustomPagesConfig',
    'conference_rooms.apps.ConferenceRoomsConfig',
    'notifier.apps.NotifierConfig',
    'absence_calendar.apps.AbsenceCalendarConfig',
    'company_structure.apps.CompanyStructureConfig',
    'glpi_integration.apps.GlpiIntegrationConfig',
    'files_management.apps.FilesManagementConfig',
    'tinymce',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'intranet_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'admin', 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intranet_project.wsgi.application'
ASGI_APPLICATION = 'intranet_project.routing.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('localhost', 6379)],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': '',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'pl'

LANGUAGES = [
    ('pl', _('Polish')),
    ('en', _('English')),
]

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = (
    '/data/locale/',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT = '/data/static/'
#STATICFILES_DIRS = [
#    os.path.join(STATIC_ROOT, 'staticfiles'),
#]

MEDIA_NAME = 'media'
MEDIA_ROOT = '/data/media/'
MEDIA_URL = '/media/'

# SMTP

EMAIL_HOST = ''
EMAIL_PORT = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_USE_SSL = True

# Microsoft Graph for Email sending

GRAPH_TENANT_ID = ''
GRAPH_CLIENT_ID = ''
GRAPH_CLIENT_SECRET = ''
GRAPH_SENDER = ''

# Setup support for proxy headers

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# DATE

DATE_BACKEND_FORMAT = '%Y-%m-%d'
DATE_FRONTEND_FORMAT_FOR_BACKEND = 'Y-m-d'

DATETIME_BACKEND_FORMAT = '%Y-%m-%d %H:%M'
DATETIME_FRONTEND_FORMAT_FOR_BACKEND = 'Y-m-d H:i'

# LIVE SETTINGS CONFIG

LIVE_SETTINGS_DIR_NAME = 'global_live_settings'
LIVE_SETTINGS_DEFAULT_LOGO_DIR_NAME = 'default'
LIVE_SETTINGS_ACTIVE_LOGO_DIR_NAME = 'active'
LIVE_SETTINGS_UPLOADS_DIR_NAME = 'uploads'

LIVE_SETTINGS_DEFAULT_LOGO_REL_DIR = os.path.join(LIVE_SETTINGS_DIR_NAME, LIVE_SETTINGS_DEFAULT_LOGO_DIR_NAME)
LIVE_SETTINGS_DEFAULT_LOGO_FILENAME = 'default_logo.png'
LIVE_SETTINGS_DEFAULT_LOGO_URL = MEDIA_URL + LIVE_SETTINGS_DIR_NAME + '/' + LIVE_SETTINGS_DEFAULT_LOGO_DIR_NAME + '/' + LIVE_SETTINGS_DEFAULT_LOGO_FILENAME

LIVE_SETTINGS_ACTIVE_LOGO_REL_DIR = os.path.join(LIVE_SETTINGS_DIR_NAME, LIVE_SETTINGS_ACTIVE_LOGO_DIR_NAME)
LIVE_SETTINGS_ACTIVE_LOGO_FILENAME = 'active_logo.png'
LIVE_SETTINGS_ACTIVE_LOGO_URL = MEDIA_URL + LIVE_SETTINGS_DIR_NAME + '/' + LIVE_SETTINGS_ACTIVE_LOGO_DIR_NAME + '/' + LIVE_SETTINGS_ACTIVE_LOGO_FILENAME

LIVE_SETTINGS_UPLOAD_REL_DIR = os.path.join(LIVE_SETTINGS_DIR_NAME, LIVE_SETTINGS_UPLOADS_DIR_NAME)

# FILES MANAGEMENT CONFIG

FILES_MANAGEMENT_DIR_NAME = 'uploads'

# ARCHIVE FILES DIR, NOT MEANT TO BE ACCESSED BY WEB APP, JUST DIRECTLY IN SERVER

ARCHIVE_DIR = '/data/files_archive/'

# ABSENCE CALENDAR CONFIG

ABSENCE_CALENDAR_VACATION_LEAVE_APPLICATIONS_DIR = os.path.join(ARCHIVE_DIR, 'absence_calendar', 'documents', 'vacation_leaves')
ABSENCE_CALENDAR_SPECIAL_LEAVE_APPLICATIONS_DIR = os.path.join(ARCHIVE_DIR, 'absence_calendar', 'documents', 'special_leaves')

# WYSIWYG CONFIG - TINYMCE

TINYMCE_DEFAULT_CONFIG = {
    'height': 600,
    'cleanup_on_startup': True,
    'custom_undo_redo_levels': 20,
    'selector': 'textarea',
    'relative_urls': False,
    'remove_script_host': False,
    'convert_urls': True,
    'plugins':
        '''
        save link image media preview codesample 
        table code lists fullscreen insertdatetime nonbreaking 
        directionality searchreplace wordcount visualblocks 
        visualchars fullscreen autolink lists charmap print hr 
        anchor pagebreak advlist paste help textcolor
        ''',
    'toolbar1':
        '''
        undo redo | fullscreen preview bold italic underline | fontselect 
        fontsizeselect | forecolor backcolor | alignleft alignright 
        aligncenter alignjustify | indent outdent | bullist numlist table | 
        link image media | charmap hr pagebreak nonbreaking anchor | 
        visualblocks visualchars removeformat | codesample code | help
        ''',
    'contextmenu': 'formats | link image',
    'menubar': True,
    'statusbar': True,
    'branding': False,
    'language': LANGUAGE_CODE,
    'file_picker_callback': 'intranetFilePicker',
}

TINYMCE_EXTRA_MEDIA = {
    'js': [
        'intranet/js/tinymce_callbacks.js',
    ],
}

# DJANGO MESSAGES

MESSAGE_TAGS = {
    message_constants.DEBUG: 'debug',
    message_constants.INFO: 'info',
    message_constants.SUCCESS: 'success',
    message_constants.WARNING: 'warning',
    message_constants.ERROR: 'danger',
}

# OTHER

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'intranet:home'
LOGIN_URL = 'users:login'

# logging

LOGGING_PATH = '/data/logs/'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_django': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'django.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_django.request': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'django.request.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_glpi_integration': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'glpi_integration.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_django_auth_ldap': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'django_auth_ldap.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_files_management': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'files_management.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_live_settings': {
            'level': 'WARNING',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'live_settings.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_absence_calendar': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'absence_calendar.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_notifier': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'notifier.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
        'file_scheduler': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGGING_PATH, 'scheduler.log'),
            'maxBytes': 1024*1024*10,
            'backupCount': 5,
            'formatter': 'verbose'
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_django'],
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file_django.request'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django_auth_ldap': {
            'handlers': ['console', 'file_django_auth_ldap'],
            'level': 'WARNING',
        },
        'glpi_integration': {
            'handlers': ['console', 'file_glpi_integration'],
            'level': 'WARNING',
        },
        'files_management': {
            'handlers': ['console', 'file_files_management'],
            'level': 'WARNING',
        },
        'live_settings': {
            'handlers': ['console', 'file_live_settings'],
            'level': 'WARNING',
        },
        'absence_calendar': {
            'handlers': ['console', 'file_absence_calendar'],
            'level': 'WARNING',
        },
        'notifier': {
            'handlers': ['console', 'file_notifier'],
            'level': 'INFO',
        },
        'scheduler': {
            'handlers': ['console', 'file_scheduler'],
            'level': 'INFO',
        }
    }
}
