# Generated by Django 3.1.2 on 2021-10-21 12:27

import conference_rooms.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='name')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('position', models.PositiveSmallIntegerField(verbose_name='position')),
            ],
            options={
                'verbose_name': 'conference room',
                'verbose_name_plural': 'conference rooms',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='tytuł')),
                ('date', models.DateField(validators=[conference_rooms.models.validate_date], verbose_name='date')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='status')),
                ('last_status_change_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='last status change time')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('conference_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_rooms.conferenceroom', verbose_name='conference room')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creator', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('status_changed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Moderator', to=settings.AUTH_USER_MODEL, verbose_name='status changed by')),
            ],
            options={
                'verbose_name': 'meeting',
                'verbose_name_plural': 'meetings',
                'permissions': (('moderate_meeting', 'Can moderate meeting'),),
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conference_rooms.meeting', verbose_name='meeting')),
            ],
            options={
                'verbose_name': 'participant',
                'verbose_name_plural': 'participants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('visible', models.BooleanField(default=True, verbose_name='visible')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
                ('moderator_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='moderator group')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AddField(
            model_name='conferenceroom',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='conference_rooms.location', verbose_name='location'),
        ),
        migrations.AddConstraint(
            model_name='conferenceroom',
            constraint=models.UniqueConstraint(fields=('location', 'position'), name='unique_location_position'),
        ),
    ]
